from PySide6.QtCore import Signal
from PySide6.QtWidgets import QFrame, QHBoxLayout, QLabel, QPushButton, QVBoxLayout, QWidget


class WelcomePage(QWidget):
    new_project_requested = Signal()
    open_project_requested = Signal()

    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QVBoxLayout(self)
        layout.setContentsMargins(56, 56, 56, 56)
        layout.setSpacing(18)
        eyebrow = QLabel("ASTROPHOTOGRAPHY WORKSPACE")
        eyebrow.setObjectName("eyebrow")
        title = QLabel("Process a night of sky\nwithout losing the thread.")
        title.setObjectName("welcomeTitle")
        copy = QLabel("AstroBatch keeps your FITS session, processing stages, outputs, and history together in one portable project.")
        copy.setObjectName("pageIntro")
        copy.setWordWrap(True)
        layout.addWidget(eyebrow)
        layout.addWidget(title)
        layout.addWidget(copy)
        actions = QHBoxLayout()
        create = QPushButton("Create a project")
        create.setObjectName("primaryButton")
        create.clicked.connect(self.new_project_requested)
        open_project = QPushButton("Open a project")
        open_project.clicked.connect(self.open_project_requested)
        actions.addWidget(create)
        actions.addWidget(open_project)
        actions.addStretch()
        layout.addLayout(actions)
        workflow = QFrame()
        workflow.setObjectName("card")
        workflow_layout = QVBoxLayout(workflow)
        heading = QLabel("A simple, visible workflow")
        heading.setObjectName("cardTitle")
        workflow_layout.addWidget(heading)
        steps = QHBoxLayout()
        for number, title_text, text in [("01", "Set up", "Create a workspace\nand choose source frames"), ("02", "Process", "Run focused stages\nwith clear status"), ("03", "Review", "Inspect the final stack\nand FITS metadata")]:
            card = QFrame()
            card.setObjectName("workflowStep")
            card_layout = QVBoxLayout(card)
            number_label = QLabel(number)
            number_label.setObjectName("stepNumber")
            item_title = QLabel(title_text)
            item_title.setObjectName("stepTitle")
            item_copy = QLabel(text)
            item_copy.setObjectName("muted")
            card_layout.addWidget(number_label)
            card_layout.addWidget(item_title)
            card_layout.addWidget(item_copy)
            steps.addWidget(card)
        workflow_layout.addLayout(steps)
        layout.addWidget(workflow)
        layout.addStretch()
